//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationListWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityReservation
    {
        public string FacilityReservationID { get; set; }
        public string FacilityID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public string UseShortDescription { get; set; }
        public string UseDescription { get; set; }
    
        public virtual Facility Facility { get; set; }
    }
}
