//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetrieveCameraData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CameraReferenceImage
    {
        public int cameraReferenceImageID { get; set; }
        public Nullable<int> cameraID { get; set; }
        public byte[] referenceImageURL { get; set; }
        public string ReferenceURL { get; set; }
    }
}
