//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camera_Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Cameras = new HashSet<Camera>();
            this.Facilities = new HashSet<Facility>();
        }
    
        public string DepartmentID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Camera> Cameras { get; set; }
        public virtual ICollection<Facility> Facilities { get; set; }
    }
}
