//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPadKioskWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentFilter
    {
        public int DepartmentFilterID { get; set; }
        public string DepartmentID { get; set; }
        public string FilterName { get; set; }
        public string Block { get; set; }
        public string Level { get; set; }
        public string Name { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
