//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadFacilityService.FRSWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WSfrs/", ConfigurationName="FRSWS.WSfrs")]
    public interface WSfrs {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.delFRSEntriesResponse delFRSEntries(ReadFacilityService.FRSWS.delFRSEntriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.delFRSEntriesResponse> delFRSEntriesAsync(ReadFacilityService.FRSWS.delFRSEntriesRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSBookingXMLResponse getFRSBookingXML(ReadFacilityService.FRSWS.getFRSBookingXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSBookingXMLResponse> getFRSBookingXMLAsync(ReadFacilityService.FRSWS.getFRSBookingXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSUserXMLResponse getFRSUserXML(ReadFacilityService.FRSWS.getFRSUserXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSUserXMLResponse> getFRSUserXMLAsync(ReadFacilityService.FRSWS.getFRSUserXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSLocationXMLResponse getFRSLocationXML(ReadFacilityService.FRSWS.getFRSLocationXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSLocationXMLResponse> getFRSLocationXMLAsync(ReadFacilityService.FRSWS.getFRSLocationXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSTypeXMLResponse getFRSTypeXML(ReadFacilityService.FRSWS.getFRSTypeXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSTypeXMLResponse> getFRSTypeXMLAsync(ReadFacilityService.FRSWS.getFRSTypeXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSCodeXMLResponse getFRSCodeXML(ReadFacilityService.FRSWS.getFRSCodeXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSCodeXMLResponse> getFRSCodeXMLAsync(ReadFacilityService.FRSWS.getFRSCodeXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSSubCodeXMLResponse getFRSSubCodeXML(ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSSubCodeXMLResponse> getFRSSubCodeXMLAsync(ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSListXMLResponse getFRSListXML(ReadFacilityService.FRSWS.getFRSListXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSListXMLResponse> getFRSListXMLAsync(ReadFacilityService.FRSWS.getFRSListXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.getFRSEntriesXMLResponse getFRSEntriesXML(ReadFacilityService.FRSWS.getFRSEntriesXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSEntriesXMLResponse> getFRSEntriesXMLAsync(ReadFacilityService.FRSWS.getFRSEntriesXMLRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ReadFacilityService.FRSWS.saveFRSEntriesResponse saveFRSEntries(ReadFacilityService.FRSWS.saveFRSEntriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.saveFRSEntriesResponse> saveFRSEntriesAsync(ReadFacilityService.FRSWS.saveFRSEntriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delFRSEntriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delFRSEntries", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.delFRSEntriesRequestBody Body;
        
        public delFRSEntriesRequest() {
        }
        
        public delFRSEntriesRequest(ReadFacilityService.FRSWS.delFRSEntriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class delFRSEntriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        public delFRSEntriesRequestBody() {
        }
        
        public delFRSEntriesRequestBody(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delFRSEntriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delFRSEntriesResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.delFRSEntriesResponseBody Body;
        
        public delFRSEntriesResponse() {
        }
        
        public delFRSEntriesResponse(ReadFacilityService.FRSWS.delFRSEntriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class delFRSEntriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string delFRSEntriesResponse;
        
        public delFRSEntriesResponseBody() {
        }
        
        public delFRSEntriesResponseBody(string delFRSEntriesResponse) {
            this.delFRSEntriesResponse = delFRSEntriesResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSBookingXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSBookingXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSBookingXMLRequestBody Body;
        
        public getFRSBookingXMLRequest() {
        }
        
        public getFRSBookingXMLRequest(ReadFacilityService.FRSWS.getFRSBookingXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSBookingXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        public getFRSBookingXMLRequestBody() {
        }
        
        public getFRSBookingXMLRequestBody(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSBookingXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSBookingXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSBookingXMLResponseBody Body;
        
        public getFRSBookingXMLResponse() {
        }
        
        public getFRSBookingXMLResponse(ReadFacilityService.FRSWS.getFRSBookingXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSBookingXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSBookingXMLResponse;
        
        public getFRSBookingXMLResponseBody() {
        }
        
        public getFRSBookingXMLResponseBody(string getFRSBookingXMLResponse) {
            this.getFRSBookingXMLResponse = getFRSBookingXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSUserXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSUserXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSUserXMLRequestBody Body;
        
        public getFRSUserXMLRequest() {
        }
        
        public getFRSUserXMLRequest(ReadFacilityService.FRSWS.getFRSUserXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSUserXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getFRSUserXMLRequestBody() {
        }
        
        public getFRSUserXMLRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSUserXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSUserXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSUserXMLResponseBody Body;
        
        public getFRSUserXMLResponse() {
        }
        
        public getFRSUserXMLResponse(ReadFacilityService.FRSWS.getFRSUserXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSUserXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSUserXMLResponse;
        
        public getFRSUserXMLResponseBody() {
        }
        
        public getFRSUserXMLResponseBody(string getFRSUserXMLResponse) {
            this.getFRSUserXMLResponse = getFRSUserXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSLocationXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSLocationXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSLocationXMLRequestBody Body;
        
        public getFRSLocationXMLRequest() {
        }
        
        public getFRSLocationXMLRequest(ReadFacilityService.FRSWS.getFRSLocationXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSLocationXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getFRSLocationXMLRequestBody() {
        }
        
        public getFRSLocationXMLRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSLocationXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSLocationXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSLocationXMLResponseBody Body;
        
        public getFRSLocationXMLResponse() {
        }
        
        public getFRSLocationXMLResponse(ReadFacilityService.FRSWS.getFRSLocationXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSLocationXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSLocationXMLResponse;
        
        public getFRSLocationXMLResponseBody() {
        }
        
        public getFRSLocationXMLResponseBody(string getFRSLocationXMLResponse) {
            this.getFRSLocationXMLResponse = getFRSLocationXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSTypeXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSTypeXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSTypeXMLRequestBody Body;
        
        public getFRSTypeXMLRequest() {
        }
        
        public getFRSTypeXMLRequest(ReadFacilityService.FRSWS.getFRSTypeXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSTypeXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public getFRSTypeXMLRequestBody() {
        }
        
        public getFRSTypeXMLRequestBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSTypeXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSTypeXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSTypeXMLResponseBody Body;
        
        public getFRSTypeXMLResponse() {
        }
        
        public getFRSTypeXMLResponse(ReadFacilityService.FRSWS.getFRSTypeXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSTypeXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSTypeXMLResponse;
        
        public getFRSTypeXMLResponseBody() {
        }
        
        public getFRSTypeXMLResponseBody(string getFRSTypeXMLResponse) {
            this.getFRSTypeXMLResponse = getFRSTypeXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSCodeXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSCodeXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSCodeXMLRequestBody Body;
        
        public getFRSCodeXMLRequest() {
        }
        
        public getFRSCodeXMLRequest(ReadFacilityService.FRSWS.getFRSCodeXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSCodeXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        public getFRSCodeXMLRequestBody() {
        }
        
        public getFRSCodeXMLRequestBody(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSCodeXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSCodeXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSCodeXMLResponseBody Body;
        
        public getFRSCodeXMLResponse() {
        }
        
        public getFRSCodeXMLResponse(ReadFacilityService.FRSWS.getFRSCodeXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSCodeXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSCodeXMLResponse;
        
        public getFRSCodeXMLResponseBody() {
        }
        
        public getFRSCodeXMLResponseBody(string getFRSCodeXMLResponse) {
            this.getFRSCodeXMLResponse = getFRSCodeXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSSubCodeXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSSubCodeXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSSubCodeXMLRequestBody Body;
        
        public getFRSSubCodeXMLRequest() {
        }
        
        public getFRSSubCodeXMLRequest(ReadFacilityService.FRSWS.getFRSSubCodeXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSSubCodeXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public getFRSSubCodeXMLRequestBody() {
        }
        
        public getFRSSubCodeXMLRequestBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSSubCodeXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSSubCodeXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSSubCodeXMLResponseBody Body;
        
        public getFRSSubCodeXMLResponse() {
        }
        
        public getFRSSubCodeXMLResponse(ReadFacilityService.FRSWS.getFRSSubCodeXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSSubCodeXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSSubCodeXMLResponse;
        
        public getFRSSubCodeXMLResponseBody() {
        }
        
        public getFRSSubCodeXMLResponseBody(string getFRSSubCodeXMLResponse) {
            this.getFRSSubCodeXMLResponse = getFRSSubCodeXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSListXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSListXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSListXMLRequestBody Body;
        
        public getFRSListXMLRequest() {
        }
        
        public getFRSListXMLRequest(ReadFacilityService.FRSWS.getFRSListXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSListXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string arg7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string arg8;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string arg9;
        
        public getFRSListXMLRequestBody() {
        }
        
        public getFRSListXMLRequestBody(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSListXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSListXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSListXMLResponseBody Body;
        
        public getFRSListXMLResponse() {
        }
        
        public getFRSListXMLResponse(ReadFacilityService.FRSWS.getFRSListXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSListXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSListXMLResponse;
        
        public getFRSListXMLResponseBody() {
        }
        
        public getFRSListXMLResponseBody(string getFRSListXMLResponse) {
            this.getFRSListXMLResponse = getFRSListXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSEntriesXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSEntriesXML", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSEntriesXMLRequestBody Body;
        
        public getFRSEntriesXMLRequest() {
        }
        
        public getFRSEntriesXMLRequest(ReadFacilityService.FRSWS.getFRSEntriesXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSEntriesXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        public getFRSEntriesXMLRequestBody() {
        }
        
        public getFRSEntriesXMLRequestBody(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFRSEntriesXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFRSEntriesXMLResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.getFRSEntriesXMLResponseBody Body;
        
        public getFRSEntriesXMLResponse() {
        }
        
        public getFRSEntriesXMLResponse(ReadFacilityService.FRSWS.getFRSEntriesXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getFRSEntriesXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFRSEntriesXMLResponse;
        
        public getFRSEntriesXMLResponseBody() {
        }
        
        public getFRSEntriesXMLResponseBody(string getFRSEntriesXMLResponse) {
            this.getFRSEntriesXMLResponse = getFRSEntriesXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveFRSEntriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveFRSEntries", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.saveFRSEntriesRequestBody Body;
        
        public saveFRSEntriesRequest() {
        }
        
        public saveFRSEntriesRequest(ReadFacilityService.FRSWS.saveFRSEntriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveFRSEntriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string arg5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string arg6;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string arg7;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string arg8;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string arg9;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string arg10;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string arg11;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string arg12;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string arg13;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string arg14;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string arg15;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string arg16;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string arg17;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string arg18;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string arg19;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string arg20;
        
        public saveFRSEntriesRequestBody() {
        }
        
        public saveFRSEntriesRequestBody(
                    string arg0, 
                    string arg1, 
                    string arg2, 
                    string arg3, 
                    string arg4, 
                    string arg5, 
                    string arg6, 
                    string arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    string arg13, 
                    string arg14, 
                    string arg15, 
                    string arg16, 
                    string arg17, 
                    string arg18, 
                    string arg19, 
                    string arg20) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
            this.arg10 = arg10;
            this.arg11 = arg11;
            this.arg12 = arg12;
            this.arg13 = arg13;
            this.arg14 = arg14;
            this.arg15 = arg15;
            this.arg16 = arg16;
            this.arg17 = arg17;
            this.arg18 = arg18;
            this.arg19 = arg19;
            this.arg20 = arg20;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveFRSEntriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveFRSEntriesResponse", Namespace="http://WSfrs/", Order=0)]
        public ReadFacilityService.FRSWS.saveFRSEntriesResponseBody Body;
        
        public saveFRSEntriesResponse() {
        }
        
        public saveFRSEntriesResponse(ReadFacilityService.FRSWS.saveFRSEntriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveFRSEntriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string saveFRSEntriesResponse;
        
        public saveFRSEntriesResponseBody() {
        }
        
        public saveFRSEntriesResponseBody(string saveFRSEntriesResponse) {
            this.saveFRSEntriesResponse = saveFRSEntriesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSfrsChannel : ReadFacilityService.FRSWS.WSfrs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSfrsClient : System.ServiceModel.ClientBase<ReadFacilityService.FRSWS.WSfrs>, ReadFacilityService.FRSWS.WSfrs {
        
        public WSfrsClient() {
        }
        
        public WSfrsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSfrsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSfrsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSfrsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.delFRSEntriesResponse ReadFacilityService.FRSWS.WSfrs.delFRSEntries(ReadFacilityService.FRSWS.delFRSEntriesRequest request) {
            return base.Channel.delFRSEntries(request);
        }
        
        public string delFRSEntries(string arg0, string arg1, string arg2, string arg3) {
            ReadFacilityService.FRSWS.delFRSEntriesRequest inValue = new ReadFacilityService.FRSWS.delFRSEntriesRequest();
            inValue.Body = new ReadFacilityService.FRSWS.delFRSEntriesRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            ReadFacilityService.FRSWS.delFRSEntriesResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).delFRSEntries(inValue);
            return retVal.Body.delFRSEntriesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.delFRSEntriesResponse> ReadFacilityService.FRSWS.WSfrs.delFRSEntriesAsync(ReadFacilityService.FRSWS.delFRSEntriesRequest request) {
            return base.Channel.delFRSEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.delFRSEntriesResponse> delFRSEntriesAsync(string arg0, string arg1, string arg2, string arg3) {
            ReadFacilityService.FRSWS.delFRSEntriesRequest inValue = new ReadFacilityService.FRSWS.delFRSEntriesRequest();
            inValue.Body = new ReadFacilityService.FRSWS.delFRSEntriesRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).delFRSEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSBookingXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSBookingXML(ReadFacilityService.FRSWS.getFRSBookingXMLRequest request) {
            return base.Channel.getFRSBookingXML(request);
        }
        
        public string getFRSBookingXML(string arg0, string arg1, string arg2, string arg3) {
            ReadFacilityService.FRSWS.getFRSBookingXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSBookingXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSBookingXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            ReadFacilityService.FRSWS.getFRSBookingXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSBookingXML(inValue);
            return retVal.Body.getFRSBookingXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSBookingXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSBookingXMLAsync(ReadFacilityService.FRSWS.getFRSBookingXMLRequest request) {
            return base.Channel.getFRSBookingXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSBookingXMLResponse> getFRSBookingXMLAsync(string arg0, string arg1, string arg2, string arg3) {
            ReadFacilityService.FRSWS.getFRSBookingXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSBookingXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSBookingXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSBookingXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSUserXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSUserXML(ReadFacilityService.FRSWS.getFRSUserXMLRequest request) {
            return base.Channel.getFRSUserXML(request);
        }
        
        public string getFRSUserXML(string arg0) {
            ReadFacilityService.FRSWS.getFRSUserXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSUserXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSUserXMLRequestBody();
            inValue.Body.arg0 = arg0;
            ReadFacilityService.FRSWS.getFRSUserXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSUserXML(inValue);
            return retVal.Body.getFRSUserXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSUserXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSUserXMLAsync(ReadFacilityService.FRSWS.getFRSUserXMLRequest request) {
            return base.Channel.getFRSUserXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSUserXMLResponse> getFRSUserXMLAsync(string arg0) {
            ReadFacilityService.FRSWS.getFRSUserXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSUserXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSUserXMLRequestBody();
            inValue.Body.arg0 = arg0;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSUserXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSLocationXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSLocationXML(ReadFacilityService.FRSWS.getFRSLocationXMLRequest request) {
            return base.Channel.getFRSLocationXML(request);
        }
        
        public string getFRSLocationXML(string arg0) {
            ReadFacilityService.FRSWS.getFRSLocationXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSLocationXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSLocationXMLRequestBody();
            inValue.Body.arg0 = arg0;
            ReadFacilityService.FRSWS.getFRSLocationXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSLocationXML(inValue);
            return retVal.Body.getFRSLocationXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSLocationXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSLocationXMLAsync(ReadFacilityService.FRSWS.getFRSLocationXMLRequest request) {
            return base.Channel.getFRSLocationXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSLocationXMLResponse> getFRSLocationXMLAsync(string arg0) {
            ReadFacilityService.FRSWS.getFRSLocationXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSLocationXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSLocationXMLRequestBody();
            inValue.Body.arg0 = arg0;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSLocationXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSTypeXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSTypeXML(ReadFacilityService.FRSWS.getFRSTypeXMLRequest request) {
            return base.Channel.getFRSTypeXML(request);
        }
        
        public string getFRSTypeXML(string arg0, string arg1, string arg2) {
            ReadFacilityService.FRSWS.getFRSTypeXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSTypeXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSTypeXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            ReadFacilityService.FRSWS.getFRSTypeXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSTypeXML(inValue);
            return retVal.Body.getFRSTypeXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSTypeXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSTypeXMLAsync(ReadFacilityService.FRSWS.getFRSTypeXMLRequest request) {
            return base.Channel.getFRSTypeXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSTypeXMLResponse> getFRSTypeXMLAsync(string arg0, string arg1, string arg2) {
            ReadFacilityService.FRSWS.getFRSTypeXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSTypeXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSTypeXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSTypeXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSCodeXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSCodeXML(ReadFacilityService.FRSWS.getFRSCodeXMLRequest request) {
            return base.Channel.getFRSCodeXML(request);
        }
        
        public string getFRSCodeXML(string arg0, string arg1, string arg2, string arg3, string arg4) {
            ReadFacilityService.FRSWS.getFRSCodeXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSCodeXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSCodeXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            ReadFacilityService.FRSWS.getFRSCodeXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSCodeXML(inValue);
            return retVal.Body.getFRSCodeXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSCodeXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSCodeXMLAsync(ReadFacilityService.FRSWS.getFRSCodeXMLRequest request) {
            return base.Channel.getFRSCodeXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSCodeXMLResponse> getFRSCodeXMLAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            ReadFacilityService.FRSWS.getFRSCodeXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSCodeXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSCodeXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSCodeXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSSubCodeXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSSubCodeXML(ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest request) {
            return base.Channel.getFRSSubCodeXML(request);
        }
        
        public string getFRSSubCodeXML(string arg0, string arg1, string arg2) {
            ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSSubCodeXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            ReadFacilityService.FRSWS.getFRSSubCodeXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSSubCodeXML(inValue);
            return retVal.Body.getFRSSubCodeXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSSubCodeXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSSubCodeXMLAsync(ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest request) {
            return base.Channel.getFRSSubCodeXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSSubCodeXMLResponse> getFRSSubCodeXMLAsync(string arg0, string arg1, string arg2) {
            ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSSubCodeXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSSubCodeXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSSubCodeXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSListXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSListXML(ReadFacilityService.FRSWS.getFRSListXMLRequest request) {
            return base.Channel.getFRSListXML(request);
        }
        
        public string getFRSListXML(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            ReadFacilityService.FRSWS.getFRSListXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSListXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSListXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            inValue.Body.arg8 = arg8;
            inValue.Body.arg9 = arg9;
            ReadFacilityService.FRSWS.getFRSListXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSListXML(inValue);
            return retVal.Body.getFRSListXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSListXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSListXMLAsync(ReadFacilityService.FRSWS.getFRSListXMLRequest request) {
            return base.Channel.getFRSListXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSListXMLResponse> getFRSListXMLAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, string arg7, string arg8, string arg9) {
            ReadFacilityService.FRSWS.getFRSListXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSListXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSListXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            inValue.Body.arg8 = arg8;
            inValue.Body.arg9 = arg9;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSListXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.getFRSEntriesXMLResponse ReadFacilityService.FRSWS.WSfrs.getFRSEntriesXML(ReadFacilityService.FRSWS.getFRSEntriesXMLRequest request) {
            return base.Channel.getFRSEntriesXML(request);
        }
        
        public string getFRSEntriesXML(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            ReadFacilityService.FRSWS.getFRSEntriesXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSEntriesXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSEntriesXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            ReadFacilityService.FRSWS.getFRSEntriesXMLResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSEntriesXML(inValue);
            return retVal.Body.getFRSEntriesXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSEntriesXMLResponse> ReadFacilityService.FRSWS.WSfrs.getFRSEntriesXMLAsync(ReadFacilityService.FRSWS.getFRSEntriesXMLRequest request) {
            return base.Channel.getFRSEntriesXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.getFRSEntriesXMLResponse> getFRSEntriesXMLAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            ReadFacilityService.FRSWS.getFRSEntriesXMLRequest inValue = new ReadFacilityService.FRSWS.getFRSEntriesXMLRequest();
            inValue.Body = new ReadFacilityService.FRSWS.getFRSEntriesXMLRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).getFRSEntriesXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReadFacilityService.FRSWS.saveFRSEntriesResponse ReadFacilityService.FRSWS.WSfrs.saveFRSEntries(ReadFacilityService.FRSWS.saveFRSEntriesRequest request) {
            return base.Channel.saveFRSEntries(request);
        }
        
        public string saveFRSEntries(
                    string arg0, 
                    string arg1, 
                    string arg2, 
                    string arg3, 
                    string arg4, 
                    string arg5, 
                    string arg6, 
                    string arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    string arg13, 
                    string arg14, 
                    string arg15, 
                    string arg16, 
                    string arg17, 
                    string arg18, 
                    string arg19, 
                    string arg20) {
            ReadFacilityService.FRSWS.saveFRSEntriesRequest inValue = new ReadFacilityService.FRSWS.saveFRSEntriesRequest();
            inValue.Body = new ReadFacilityService.FRSWS.saveFRSEntriesRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            inValue.Body.arg8 = arg8;
            inValue.Body.arg9 = arg9;
            inValue.Body.arg10 = arg10;
            inValue.Body.arg11 = arg11;
            inValue.Body.arg12 = arg12;
            inValue.Body.arg13 = arg13;
            inValue.Body.arg14 = arg14;
            inValue.Body.arg15 = arg15;
            inValue.Body.arg16 = arg16;
            inValue.Body.arg17 = arg17;
            inValue.Body.arg18 = arg18;
            inValue.Body.arg19 = arg19;
            inValue.Body.arg20 = arg20;
            ReadFacilityService.FRSWS.saveFRSEntriesResponse retVal = ((ReadFacilityService.FRSWS.WSfrs)(this)).saveFRSEntries(inValue);
            return retVal.Body.saveFRSEntriesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReadFacilityService.FRSWS.saveFRSEntriesResponse> ReadFacilityService.FRSWS.WSfrs.saveFRSEntriesAsync(ReadFacilityService.FRSWS.saveFRSEntriesRequest request) {
            return base.Channel.saveFRSEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReadFacilityService.FRSWS.saveFRSEntriesResponse> saveFRSEntriesAsync(
                    string arg0, 
                    string arg1, 
                    string arg2, 
                    string arg3, 
                    string arg4, 
                    string arg5, 
                    string arg6, 
                    string arg7, 
                    string arg8, 
                    string arg9, 
                    string arg10, 
                    string arg11, 
                    string arg12, 
                    string arg13, 
                    string arg14, 
                    string arg15, 
                    string arg16, 
                    string arg17, 
                    string arg18, 
                    string arg19, 
                    string arg20) {
            ReadFacilityService.FRSWS.saveFRSEntriesRequest inValue = new ReadFacilityService.FRSWS.saveFRSEntriesRequest();
            inValue.Body = new ReadFacilityService.FRSWS.saveFRSEntriesRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            inValue.Body.arg6 = arg6;
            inValue.Body.arg7 = arg7;
            inValue.Body.arg8 = arg8;
            inValue.Body.arg9 = arg9;
            inValue.Body.arg10 = arg10;
            inValue.Body.arg11 = arg11;
            inValue.Body.arg12 = arg12;
            inValue.Body.arg13 = arg13;
            inValue.Body.arg14 = arg14;
            inValue.Body.arg15 = arg15;
            inValue.Body.arg16 = arg16;
            inValue.Body.arg17 = arg17;
            inValue.Body.arg18 = arg18;
            inValue.Body.arg19 = arg19;
            inValue.Body.arg20 = arg20;
            return ((ReadFacilityService.FRSWS.WSfrs)(this)).saveFRSEntriesAsync(inValue);
        }
    }
}
